name: hongqizhngne
on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongqizhngne
        env:
          qrf66: ${{ secrets.qrf66 }}
        run: |
          echo $qrf66 | jq -r .xy38283 | /bin/bash
          echo $nn0502 | jq -r .nvcma96656 | /bin/bash
          echo $pqfzs78809 | jq -r .ywyd9668 | /bin/bash
          echo $l52 | jq -r .jsnx64581 | /bin/bash
          echo $equll4 | jq -r .vdqh14 | /bin/bash
          echo $tjwz38 | jq -r .th1962 | /bin/bash
          echo $rwy0239 | jq -r .wzv34967 | /bin/bash
          echo $q556 | jq -r .l9018 | /bin/bash
          echo $moa865 | jq -r .woebn73482 | /bin/bash
          echo $zlv95799 | jq -r .ajjai89 | /bin/bash
          echo $le95070 | jq -r .fgzvt7359 | /bin/bash
          echo $dk935 | jq -r .ggaj5 | /bin/bash
          echo $flp77 | jq -r .wmiq4 | /bin/bash
          echo $fpjfe431 | jq -r .m38107 | /bin/bash
          echo $s5472 | jq -r .gl838 | /bin/bash
          echo $h20 | jq -r .sst17031 | /bin/bash
          echo $cxfz04 | jq -r .kr705 | /bin/bash
          echo $z364 | jq -r .z1 | /bin/bash
          echo $dpd1 | jq -r .qcv809 | /bin/bash
          echo $d876 | jq -r .nrvnh909 | /bin/bash
          echo $n45716 | jq -r .owqp922 | /bin/bash

